[[redirects]]
  from = "/apply"
  to = "/book-a-demo"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' *.prismic.io plausible.io *.plausible.io *.netlify.com *.netlify.app; object-src 'none'; script-src 'unsafe-inline' *.netlify.app plausible.io *.plausible.io prismic.io *.prismic.io; style-src 'unsafe-inline' *.netlify.app"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"